### ISSUE TITLE
Support for scrolling with mouse

### ISSUE THREAD

**Issue by rygwdn** [coolwanglu/neovim.as#12]
neovim TUI and vanilla `gvim` both support scrolling with the mouse, would be nice to have that in neovim.as too.

**Comment by coolwanglu** [comment]
Right.
One difficult thing is that the scroll event is different across systems, I'll check how Atom is handling it.

**Comment by coolwanglu** [comment]
@rygwdn which platform were you working on? There are a few issues reported that scrolling is not working on Ubuntu.

**Comment by rygwdn** [comment]
I've only tested on OS X
