### ISSUE TITLE
in Windows the window resizes to minimal size on its own

### ISSUE THREAD

**Issue by jmlucjav** [coolwanglu/neovim.as#16]
Hi,

I tried to run this on windows. I was more or less successful, but found one weird issue for now.
First a big caveat, I am not comfortable in the js/coffescript world, so not sure if I did everything as needed, probably screwed up somewhere...

What I did was:
- I already had node-js installed
- download neovim build for windows from appveyor
- download atom-shell build for windows
- download neovim-as
- npm install -g grunt-cli
- cd neovim.as
- path-to-atom\resources\app\apm\bin\apm.cmd build .
  
  I had Atom too, and found apm in there, so I used it
- grunt
- copy nvim.exe to neovim.as\
- path-to-atom-shell\atom.exe .
  
  this is different from you instructions, in windows at least there is no 'atom-shell.exe', just 'atom.exe'.

This successfully launches neovim.as with nvim. But the window resizes by itself most of the time time it is tiny, see the video here: http://tinypic.com/player.php?v=2wgxb1c&s=8#.VOmxqVXF-zY

Other than that, seem usable, I can enter insert mode etc.

**Comment by coolwanglu** [comment]
I see, something still wrong with the resize event handler.

**Comment by rygwdn** [comment]
@coolwanglu that looks similar to something I saw while working on #13. I suspect that what's happening is:
- window resize event triggers, and tells nvim to resize to `NxM` rows/cols
- nvim resizes and triggers `nv_resize`
- `nv_resize` calls `window.resizeTo` which triggers the window resize event again

This is not a problem for OS X (and I assume Linux?), but if the calculation of window size in `nv_size` produces a window that's too small, then it will trigger a loop that keeps reducing the rows/cols until it hits a minimum size.

#13 _may_ fix this (I changed the conditions under which `nv_resize` calls `window.resizeTo`)

**Comment by jmlucjav** [comment]
@rygwdn , I tried to manually apply your change locally, but get a compilation failure:

> > In file: src/nvim/ui.coffee
> > On line: 95
> >         if not @resize_timer
> >         ^
> >    Warning: CoffeeScript failed to compile. Use --force to continue.

So I just commented out the line with the if (first time I look at coffescript code so not much else I can do). Tested and now I don't get the previous behavior.

**Comment by rygwdn** [comment]
@jmlucjav: #13 was merged, can you try `master` again?

**Comment by jmlucjav** [comment]
I just tested 2d3fc60d8768961a921bb526a71b05a91b73172a and the weird behaviour is gone. Also, I can resize the window, and it works.

Next issue I see:
- if I do :e package.json the file is loaded fine and I can edit it
- if I drag it with the mouse over the window, the file is loaded, but I loose control of the cursor, I cannot do anything more, Esc and i don't change mode and there is no cursor visible.

I have not tried loadding my _vimrc yet, will try another time.

**Comment by jmlucjav** [comment]
should I close this and open a new issue or we can reuse this for 'all things Windows'?

**Comment by coolwanglu** [comment]
@jmlucjav Please create a new issue for this, thanks!
