### ISSUE TITLE
Mouse scrolling background glitch

### ISSUE THREAD

**Issue by averrin** [coolwanglu/neovim.as#21]
![neovim_as_mousescroll](https://cloud.githubusercontent.com/assets/426007/6638384/740fd60a-c996-11e4-9175-2b801d395bf4.png)

it fixes by keyboard scrolling.

**Comment by coolwanglu** [comment]
How do you reproduce this effect? And what's the colorscheme you are using?

**Comment by averrin** [comment]
On Ubuntu 14.04, with default scheme (on screenshot) and with molokai (but background is gray instead black).
Just launch and scroll with mouse wheel.

**Comment by coolwanglu** [comment]
I cannot reproduce this on Mac, and unfortunately I don't have a Ubuntu to test. 
Hope that some one will be able to diagnose this issue.

**Comment by syswow** [comment]
I can reproduce this on Ubuntu 14.04 x64. It may be a **random** bug.

Reproduce steps(only 1):
- neovim.as open a file.

Pics: 
![render-1](https://cloud.githubusercontent.com/assets/10815286/6655337/d2710e70-cb36-11e4-8b81-5bc072efb231.png)

![render-2](https://cloud.githubusercontent.com/assets/10815286/6655348/4936aefc-cb37-11e4-8267-8984cfc30eb9.png)

**Comment by rygwdn** [comment]
I can reproduce this on OS X, I see it when moving around in the file without the mouse too (just holding `<j>`)

**Comment by rygwdn** [comment]
Looks like (for me at least), the color that's getting filled is the background color of the bottom-right block (in my case my airline status line). When the scroll event comes in, it looks like it's setting the background of the new area to match that instead of the actual background color. I'll have a PR up shortly that should fix it

**Comment by syswow** [comment]
Thank you, It works really well now. :cat:
