### ISSUE TITLE
<C-c> and similar not forwarded to vim

### ISSUE THREAD

**Issue by neojski** [coolwanglu/neovim.as#3]
I expected `<c-c>` to work but it looks like `atom-shell` is preventing then somehow. They don't show-up in the `addEventListener` callback.

**Comment by coolwanglu** [comment]
I try to type `:bla` and then `<C-c>`, and the command-line is cancelled as expected.
It might be the differences of the behavior of Chrome in different OSes. Which OS are you using?

**Comment by rygwdn** [comment]
`<C-space>` doesn't appear to get forwarded to neovim either.

**Comment by neojski** [comment]
`:bla<C-c>` does not work either. I'm using archlinux. It looks like `<C-r>` works. I'm not sure why this is happening.

**Comment by coolwanglu** [comment]
I see, I think that the key codes might need special checks across different OSes. I think I'll need to collect more information, or to find a library for this task.

**Comment by coolwanglu** [comment]
@rygwdn yeah, I found that both `charCode` and `keyCode` are 0 for the keypress event of  `<C-space>`, I might need to capture `keydown` events for this.

**Comment by coolwanglu** [comment]
I have integrated the functions of `atom-keymap`, hopefully it's better now. But a side-effect is that `caps-lock` is now ignored.
It has been pushed to the `master` branch, please give a try.

**Comment by rygwdn** [comment]
@coolwanglu I tried out the `master` branch and unfortunately `<C-Space>` still does nothing.

**Comment by rygwdn** [comment]
disregard that last comment, it does indeed work! (I forgot to re-generate the JS from coffeescript).

**Comment by coolwanglu** [comment]
@rygwdn great!

**Comment by coolwanglu** [comment]
@neojski Could you test `<c-c>`?

**Comment by neojski** [comment]
Works now, thanks!
