### ISSUE TITLE
Atom-shell is now called Electron, what now?

### ISSUE THREAD

**Issue by Calinou** [coolwanglu/neovim.as#31]
Do you plan to change the repository name?

http://blog.atom.io/2015/04/23/electron.html

**Comment by coolwanglu** [comment]
Thanks for the reminder.
Hmm, we need a new name, maybe neovim<sup>+</sup>?

**Comment by coolwanglu** [comment]
Oh it should be neovim<sup>-</sup>, as we have an extra electron...

**Comment by coolwanglu** [comment]
How about 

<h4>neovim<sup>+</sup>: neovim needs electron</h4>

**Comment by coolwanglu** [comment]
Hmm.. changed to `neovim-e`
