### ISSUE TITLE
Unable to pass keyboard input to neovim.as window on OS X

### ISSUE THREAD

**Issue by kopischke** [coolwanglu/neovim.as#7]
I’ve run into an odd issue where I can start _Neovim.AS_, but cannot get its window to accept keyboard input; instead, all keyboard input goes to the terminal in which _Neovim.AS_ was started.

![neovim](https://cloud.githubusercontent.com/assets/80906/6232019/c3640e22-b6c9-11e4-87c2-ba6f09075326.png)

I also can’t switch to the window with `Cmd-Tab`, its OS X menu does not display, and the only way to quit it is issuing `^C` in the originating shell.

**Configuration:**
- OS X 10.10.2 German locale, German keyboard input
- NVIM 0.0.0-alpha+201502170110 (compiled Feb 17 2015 16:17:11), commit 66a03a7385dfd11503d22d8cc9dc6a972e27dcc2, via Homebrew – Neovim itself runs fine in Terminal
- _grunt-cli_ v0.1.13 and _grunt_ v0.4.5, installed via _npm_ – running `grunt -v` inside the neovim.as directory gives no errors
- _atom-shell_ version 0.19.5 – the Atom shell app also starts fine by itself

**Comment by coolwanglu** [comment]
It seems to be that the Atom window can never get the focus?
Try clicking on it maybe?

**Comment by kopischke** [comment]
Ha, yeah, should have mentioned I did that as a matter of course :). I can click the window into the foreground, I can resize it, and the OS X window management bubbles respond to hover, but even with the window in the apparent foreground, all issues described in my original post are still present.

Is there any way I can get a log of what happens? The two console messages depicted in the screenshot aren’t very helpful…

**Comment by coolwanglu** [comment]
You can log the event by changing these event handlers:
https://github.com/coolwanglu/neovim.as/blob/master/src/nvim/ui.coffee#L120

I didn't find relevant issues in Atom Shell repo, can you run other Atom Shell apps?

**Comment by kopischke** [comment]
> can you run other Atom Shell apps?

I’d be happy to test, but I’m not aware of any (assuming you don’t means Atom itself, which runs fine) – do you happen to have a suggestion for me?

**Comment by coolwanglu** [comment]
Oh in fact I don't know other Atom Shell apps. 

I quickly reviewed the code again but did not find anything wrong, it might be about os x 10.10? (I'm using 10.9 which works fine).

Maybe you can try to hack the event listeners first, if there's nothing printed, it'll be more likely a bug of Atom Shell.

**Comment by kopischke** [comment]
OK, so it seems to be a generic issue with Atom Shell, at least with my setup. I updated Atom Shell to the latest release (0.21.2) and tested again with [another shell app](https://github.com/pamods/pamm-atom). That turned out to be responsive to mouse input, but also ignores keyboard input and has the same activation / focus issues as _Neovim.AS_. It looks like something blocks Atom Shell from detaching properly, as I cannot start an Atom Shell instance via the app bundle once the shell app runs...

I’ve also tried disabling keyboard input hacks (specifically, [Seil](https://pqrs.org/osx/karabiner/seil.html.en) and [Karabiner](https://pqrs.org/osx/karabiner/index.html.en)) and switching to US keyboard input, but none of that helped.

As I know diddly-squat about the Atom Shell API and only a little more than that about CoffeeScript, I’ll give up on getting _Neovim.AS_ to run.

**Comment by coolwanglu** [comment]
@kopischke You might file an issue for Atom Shell, the developers might be able to fix it.

**Comment by kopischke** [comment]
I filed an issue; you’ll see I have narrowed it down to Atom Shell apps launched via the CLI.

**Comment by coolwanglu** [comment]
@kopischke Thanks!

**Comment by kopischke** [comment]
@coolwanglu the base issue has been narrowed down to `atom-shell` being a symlink (see https://github.com/atom/atom-shell/issues/1151#issuecomment-92085514).

**Comment by coolwanglu** [comment]
@kopischke Thanks! That sounds like a really tricky bug.
