### ISSUE TITLE
Cursor position shifts when resizing

### ISSUE THREAD

**Issue by rygwdn** [coolwanglu/neovim.as#8]
This is pretty easy to reproduce. When I have the cursor near the right side of the window and then resize, I need to be very careful to resize the window such that the cursor remains lined up with the characters in the window, otherwise it moves off the character grid:

Working properly:
![screen shot 2015-02-20 at 7 57 25 am](https://cloud.githubusercontent.com/assets/48253/6285784/4ba83e58-b8d6-11e4-8fbe-58c3bb1a2c9d.png)

Resized horizontally:
![screen shot 2015-02-20 at 7 57 44 am](https://cloud.githubusercontent.com/assets/48253/6285783/45e32050-b8d6-11e4-9afc-4abac880a9d6.png)

The same issue happens vertically:
![screen shot 2015-02-20 at 7 58 03 am](https://cloud.githubusercontent.com/assets/48253/6285786/54d9a8c2-b8d6-11e4-93b0-d71c7a94eca7.png)

**Comment by coolwanglu** [comment]
After you resize the window (not during), did the font size become larger? 
Ideally it should not, and the number of rows/cols should change accordingly.

**Comment by rygwdn** [comment]
the font size stays the same, but the spacing (both vertical and horizontal) changes.

**Comment by coolwanglu** [comment]
fixed via #13
