### ISSUE TITLE
Support opening multiple files from command line

### ISSUE THREAD

**Issue by rygwdn** [coolwanglu/neovim.as#9]
It would be very helpful to support opening multiple files from a shell into a single neovim.as window. The editor currently only considers the first argument to be a file to open.

**Comment by coolwanglu** [comment]
Since this is a UI of neovim, I think the feature should be added to neovim directly.

**Comment by rygwdn** [comment]
I think this might have something to do with the fact that when opening multiple files with `nvim --embed file1 file2` it sends `2 files to edit` on stdout, so I agree, this looks like a neovim bug.

**Comment by coolwanglu** [comment]
I remember that vim should have the same behavior though...
